### ISSUE TITLE
Ambassador dashboard MVP

### ISSUE THREAD

**Issue by noahsark769** [calblueprint/revolv#106]
Should have:

- [x] List of Draft Projects
- [x] List of active projects which clearly show their donation progress (#117)
- [ ] List of completed projects started by the ambassador with links to update and showing repayment progres (#118, #119)

**Comment by noahsark769** [comment]
I'm gunna go ahead and close this. the ambassador dashboard is pretty much done except for #108, so I'm gunna prefer just labeling issues with ambassador-dash instead of having this issue.
