### ISSUE TITLE
Donor dashboard MVP

### ISSUE THREAD

**Issue by vivekraghuram** [calblueprint/revolv#65]
Donor dashboard should include the following:
- [x] Donated projects
- [ ] - w/ statistics for each (#108)
- [ ] Total statistics across all donated projects (#109)
- [ ] Reinvestment (#310 )
- [ ] solar-log graph (#40)
