### ISSUE TITLE
Administrator dashboard MVP

### ISSUE THREAD

**Issue by vivekraghuram** [calblueprint/revolv#66]
Style them so they look pretty :).
- [x] List of proposed projects with button to view
- [x] - or edit
- [x] List of active projects with button to view or edit and donation progress (#119)
- [ ] List of completed projects with button to view or edit and repayment progress (#117)
- [ ] place to view "votes" for reinvestment (#313)
- [ ] place to view accounting for donations and reinvesting. Note that this is for ALL projects, not per project. (#32)
